apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- namespace-course-exercises.yaml
- persistentvolume.yaml
- persistentvolumeclaim.yaml
- postgres-sealedsecret.yaml
- telegram-sealedsecret.yaml
- postgres-statefulset.yaml
- service.yaml

images:
- name: PROJECT/BACKENDIMAGE
  newName: aventusm/kube-node-project-backend
  newTag: 0a83a05986a355759ea069b8e45f821066d614a4
- name: PROJECT/BROADCASTERIMAGE
  newName: aventusm/kube-node-project-broadcaster
  newTag: 0a83a05986a355759ea069b8e45f821066d614a4
- name: PROJECT/GATEWAYIMAGE
  newName: aventusm/kube-node-project
  newTag: 0a83a05986a355759ea069b8e45f821066d614a4
