apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- namespace-course-exercises.yaml
- persistentvolume.yaml
- persistentvolumeclaim.yaml
- sealedsecret-postgres.yaml
- sealedsecret-telegram.yaml
- postgres-statefulset.yaml
- service.yaml

images:
- name: PROJECT/BACKENDIMAGE
  newName: aventusm/kube-node-project-backend
  newTag: 91b823e614989ebb949c01f6e14bc4d7bf27c3a2
- name: PROJECT/BROADCASTERIMAGE
  newName: aventusm/kube-node-project-broadcaster
  newTag: 91b823e614989ebb949c01f6e14bc4d7bf27c3a2
- name: PROJECT/GATEWAYIMAGE
  newName: aventusm/kube-node-project
  newTag: 91b823e614989ebb949c01f6e14bc4d7bf27c3a2
