apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- namespace-course-exercises.yaml
- persistentvolume.yaml
- persistentvolumeclaim.yaml
- sealedsecret-postgres.yaml
- sealedsecret-telegram.yaml
- postgres-statefulset.yaml
- service.yaml

images:
- name: PROJECT/BACKENDIMAGE
  newName: aventusm/kube-node-project-backend
  newTag: 525b85514fc53ac9fa335583131783bfcff5c947
- name: PROJECT/BROADCASTERIMAGE
  newName: aventusm/kube-node-project-broadcaster
  newTag: 525b85514fc53ac9fa335583131783bfcff5c947
- name: PROJECT/GATEWAYIMAGE
  newName: aventusm/kube-node-project
  newTag: 525b85514fc53ac9fa335583131783bfcff5c947
