apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- namespace-course-exercises.yaml
- persistentvolume.yaml
- persistentvolumeclaim.yaml
- postgres-sealedsecret.yaml
- telegram-sealedsecret.yaml
- postgres-statefulset.yaml
- service.yaml

images:
- name: PROJECT/BACKENDIMAGE
  newName: aventusm/kube-node-project-backend
  newTag: 1d23a6679246d16b5683a2e42148099a6588ff15
- name: PROJECT/BROADCASTERIMAGE
  newName: aventusm/kube-node-project-broadcaster
  newTag: 1d23a6679246d16b5683a2e42148099a6588ff15
- name: PROJECT/GATEWAYIMAGE
  newName: aventusm/kube-node-project
  newTag: 1d23a6679246d16b5683a2e42148099a6588ff15
