apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-bot
  namespace: default
spec:
  encryptedData:
    SECRET_TELEGRAM_TOKEN: AgCqwCyyA7VeTL0JLu/hTRYXL5hZ7kQTWcX8OTX+/NH170fqgBcHoN5koZZKF+XnGTWw/JUiJwLa5zIAjHjVtc7PN4NxiViCjoa5T9houbUauC63lbZ83tblQP5/2GKA1xDJbI7b74PFjRNhjAhLgXpRr1ftFFV6M2JGbzaDEh3/JjPWy3fdb1qI2yABWdH2Rdn8vAZdiJV/hPAjuVFBk6Jih3g67j6MrlFQN0Z8ERNQ6S8aOliOF+nuV7A9I7lmvFzqSHQ14AGV8eXgyPDao3GB1js8euZdObN32Qhm9580NBlsxRzEU3OfRN3XpPTE9T3E890zcUPZQ3fNSAU50mXms0NKGcg/MzGZpsJHrBCY5YBE/VSVj2vD4VzP0gDvDRUfGfZfFMITngHU/ScH1dDMG+pD7jNYRD7iwjf7n9cyKb1KOxRomwugm9BpPbHPuibWD0SX0IdSIA4G7WlqJRPY2crZ173LDAjEtyVmsUYSTTBOf1fFbdcPg36Yl7uaHM/kLycELCxUDQMmDnRdm8dFNdsM0h57u1vuDc4TD7LTR2/OP+gbR6p1JCQpmtaH/jHBp393g67UJKeIL4mL/St6aQNHzbRim3x7Ha6s5kY88WaiWLGVpI6n1mQnHRTh6CRqPHXbSeT9ZbGoNwu4NwQ+utbX73Kd4uBhDvl/3MJj9B3UeIsDftkZLtCRYInPwdK5jYgntYYKfuLShdHvMHoEabvDQHc/UutWSu2QPJPcg4PgKDQs6a1EZ6+qLl1Y
  template:
    metadata:
      creationTimestamp: null
      name: telegram-bot
      namespace: default

